spring:
  application:
    name: fs
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iammahesh123/config-repo
          #uri: https://github.com/iammahesh123/config-repo
          #clone-on-start: true
server:
  port: 8888
my :
  greeting: hello world from config server
    
